### ISSUE TITLE
[BUG] New videos will end up broken due missing ffprobe

### ISSUE THREAD

**Issue by Hely0n** [imagegenius/docker-immich#396]
When I upload a new video or refresh encoded video, the logs say:

>[Nest] 440  - 07/03/2024, 10:49:06 PM   ERROR [Microservices:JobService] Unable to run job handler (videoConversion/video-conversion): Error: Cannot find ffprobe
[Nest] 440  - 07/03/2024, 10:49:06 PM   ERROR [Microservices:JobService] Error: Cannot find ffprobe
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/ffprobe.js:145:31
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/capabilities.js:194:9
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/capabilities.js:186:13
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/utils.js:223:16
    at F (/app/immich/server/node_modules/fluent-ffmpeg/node_modules/which/which.js:68:16)
    at E (/app/immich/server/node_modules/fluent-ffmpeg/node_modules/which/which.js:80:29)
    at /app/immich/server/node_modules/fluent-ffmpeg/node_modules/which/which.js:89:16
    at /app/immich/server/node_modules/isexe/index.js:42:5
[Nest] 440  - 07/03/2024, 10:49:06 PM   ERROR [Microservices:JobService] Object:
{
  "id": "1722f35c-2d7f-4328-bb0e-4b65c4153e33"
}

The video can't be played and looks like this:

![image](https://github.com/imagegenius/docker-immich/assets/29177466/daee1850-8bc9-4289-9f76-5e347d71c017)

**Comment by martabal** [comment]
Should be fixed by updating the docker image and run the missing jobs for `EXTRACT METADATA`, ` GENERATE THUMBNAILS` and `TRANSCODE VIDEOS`

**Comment by Hely0n** [comment]
unfortunately, force-pulling latest aswell as pulling tag "v1.107.2-ig299" didn't fix it :/

**Comment by martabal** [comment]
Yes, sorry for the inconvenience, we are tracking the issue here https://github.com/imagegenius/docker-immich/issues/391#issuecomment-2207326599
